In [1]:
from pwn import *

In [2]:
r = remote('edu-ctf.csie.org', 42069)
money = 1.2

[x] Opening connection to edu-ctf.csie.org on port 42069
[x] Opening connection to edu-ctf.csie.org on port 42069: Trying 140.112.31.97
[+] Opening connection to edu-ctf.csie.org on port 42069: Done


In [3]:
def guess(ans):
    global money
    
    r.sendlineafter(b"> ", f"{ans}".encode())
    cur_money = float(r.recvline().decode().strip())
    diff = cur_money - money
    if abs(diff - (-0.04)) < 1e-4: # lose
        ans = 1

    money = cur_money
    return ans, money


round_ans = []
for _ in range(64):
    ans, money = guess(0)
    print(ans, money)
    round_ans.append(ans)

0 1.22
1 1.18
0 1.2
1 1.16
0 1.18
0 1.2
1 1.16
0 1.18
0 1.2
0 1.22
0 1.24
1 1.2
1 1.16
0 1.18
1 1.14
1 1.0999999999999999
0 1.1199999999999999
1 1.0799999999999998
1 1.0399999999999998
0 1.0599999999999998
1 1.0199999999999998
0 1.0399999999999998
1 0.9999999999999998
0 1.0199999999999998
0 1.0399999999999998
1 0.9999999999999998
0 1.0199999999999998
1 0.9799999999999998
1 0.9399999999999997
0 0.9599999999999997
0 0.9799999999999998
0 0.9999999999999998
1 0.9599999999999997
0 0.9799999999999998
0 0.9999999999999998
0 1.0199999999999998
0 1.0399999999999998
0 1.0599999999999998
0 1.0799999999999998
0 1.0999999999999999
0 1.1199999999999999
0 1.14
1 1.0999999999999999
0 1.1199999999999999
0 1.14
0 1.16
1 1.1199999999999999
1 1.0799999999999998
0 1.0999999999999999
1 1.0599999999999998
0 1.0799999999999998
1 1.0399999999999998
0 1.0599999999999998
0 1.0799999999999998
0 1.0999999999999999
1 1.0599999999999998
0 1.0799999999999998
1 1.0399999999999998
1 0.9999999999999998
1 0.9599999999999

In [4]:
round_ans

[0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [5]:
f"{0xaa0d3a677e1be0bf:0>64b}"

'1010101000001101001110100110011101111110000110111110000010111111'

In [6]:
taps_raw = f"{0xaa0d3a677e1be0bf:0>64b}"

In [7]:
P.<x> = PolynomialRing(GF(2))
P = x^64

for i, t in enumerate(taps_raw):
    if t == '1':
        P += x^i

P

x^64 + x^63 + x^62 + x^61 + x^60 + x^59 + x^58 + x^56 + x^50 + x^49 + x^48 + x^47 + x^46 + x^44 + x^43 + x^38 + x^37 + x^36 + x^35 + x^34 + x^33 + x^31 + x^30 + x^29 + x^26 + x^25 + x^22 + x^20 + x^19 + x^18 + x^15 + x^13 + x^12 + x^6 + x^4 + x^2 + 1

In [8]:
C = companion_matrix(P, format='left')
print(C.str())

[1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [9]:
M = Matrix(GF(2), 64)
V = vector(GF(2), 64)
D = C ^ 43

for idx, ans in enumerate(round_ans):
    M[idx] = (D ^ (idx+1))[0]
    V[idx] = ans

In [10]:
print(M.str())

[1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0]
[1 0 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 1 1 0]
[0 0 1 0 0 1 1 1 1 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 0 1 1 1 0 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 1 1]
[1 1 1 0 1 1 1 1 0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 1 1 1 1 0 1 1 0 0 0 0 0 0 1 1 1]
[0 0 0 1 1 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 0 1 0 1 0 1 1 0]
[1 0 0 1 0 1 1 0 0 1 0 0 1 1 1 0 0 1 1 0 1 1 0 0 1 1 1 1 0 1 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1]
[0 0 1 0 0 0 1 1 0 1 0 1 1 1 0 1 1 0 0 1 1 0 1 1 1 0 0 1 0 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 0

In [11]:
V

(0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1)

In [12]:
init_state = M ^ -1 * V

s = init_state
test = []
for _ in range(64):
    s = D * s
    test.append(s[0])
test

[0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [13]:
for _ in range(100):
    s = D * s
    ans, money = guess(s[0])
    print(ans, money)

0 0.8199999999999996
1 0.8399999999999996
0 0.8599999999999997
1 0.8799999999999997
1 0.8999999999999997
1 0.9199999999999997
1 0.9399999999999997
1 0.9599999999999997
0 0.9799999999999998
1 0.9999999999999998
0 1.0199999999999998
0 1.0399999999999998
0 1.0599999999999998
1 1.0799999999999998
1 1.0999999999999999
0 1.1199999999999999
0 1.14
0 1.16
1 1.18
1 1.2
0 1.22
0 1.24
0 1.26
1 1.28
1 1.3
1 1.32
0 1.34
0 1.36
1 1.3800000000000001
0 1.4000000000000001
1 1.4200000000000002
1 1.4400000000000002
0 1.4600000000000002
0 1.4800000000000002
0 1.5000000000000002
1 1.5200000000000002
0 1.5400000000000003
1 1.5600000000000003
1 1.5800000000000003
1 1.6000000000000003
0 1.6200000000000003
1 1.6400000000000003
1 1.6600000000000004
1 1.6800000000000004
1 1.7000000000000004
1 1.7200000000000004
1 1.7400000000000004
1 1.7600000000000005
0 1.7800000000000005
0 1.8000000000000005
1 1.8200000000000005
1 1.8400000000000005
0 1.8600000000000005
1 1.8800000000000006
0 1.9000000000000006
1 1.92000000000

EOFError: 

In [14]:
r.recvline().decode()

"Here's your flag:\n"

In [15]:
r.recvline().decode()

'FLAG{2iroO742LwA2ES1Cwewx}\n'